# repozitář B: .github/workflows/main.yml
name: Odkaz na workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: OlafHappyson/ci_templates/.github/workflows/workflow_call.yml@main
    
